version: "3"
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
  selenium-firefox:
    image: b4handjr/selenium-firefox
    ports:
      - "${VNC_PORT:-5900}:5900"
    shm_size: 2g
    volumes:
      - .:/code
